manipulator:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
  projection_evaluator: joints(shoulder_lift_link)
  longest_valid_segment_fraction: 0.05

planner_configs:

  SBLkConfigDefault:
    type: geometric::SBL

  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
