# Joints limits

limits:
  shoulder_pan:
    lower: -6.28318530718
    upper: 6.28318530718
    velocity: 2.16
    effort: 330.0
  shoulder_lift:
    lower: -6.28318530718
    upper: 6.28318530718
    velocity: 2.16
    effort: 330.0
  elbow_joint:
    lower: -3.14159265359
    upper: 3.14159265359
    velocity: 3.15
    effort: 150.0
  wrist_1:
    lower: -6.28318530718
    upper: 6.28318530718
    velocity: 3.2
    effort: 54.0
  wrist_2:
    lower: -6.28318530718
    upper: 6.28318530718
    velocity: 3.2
    effort: 54.0
  wrist_3:
    lower: -6.28318530718
    upper: 6.28318530718
    velocity: 3.2
    effort: 54.0