joint_limits:
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: false
    max_acceleration: 0
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.16
    has_acceleration_limits: false
    max_acceleration: 0