# Physical parameters

# from https://www.universal-robots.com/how-tos-and-faqs/faq/ur-faq/parameters-for-calculations-of-kinematics-and-dynamics-45257/
dh_parameters:
  d1: 0.1807
  a2: -0.4784
  a3: -0.36
  d4: 0.17415
  d5: 0.11985
  d6: 0.11655

offsets:
  shoulder_offset: 0.176 # measured from model
  elbow_offset: 0.040 # measured from model

inertia_parameters:
  # taken from https://www.universal-robots.com/how-tos-and-faqs/faq/ur-faq/parameters-for-calculations-of-kinematics-and-dynamics-45257/
  base_mass: 4.0  # This mass might be incorrect
  shoulder_mass: 7.369
  upper_arm_mass: 10.450
  upper_arm_inertia_offset: 0.175 # measured from model
  forearm_mass: 4.321
  wrist_1_mass: 2.180
  wrist_2_mass: 2.033
  wrist_3_mass: 0.907

  shoulder_radius: x0.060   # FROM UR5 CURRENTLY NOT USED ANYMORE
  upper_arm_radius: x0.054  # FROM UR5 CURRENTLY NOT USED ANYMORE
  elbow_radius: x0.060      # FROM UR5 CURRENTLY NOT USED ANYMORE
  forearm_radius: x0.040    # FROM UR5 CURRENTLY NOT USED ANYMORE
  wrist_radius: x0.045      # FROM UR5 CURRENTLY NOT USED ANYMORE

  links:
    base:
      radius: 0.075
      length: 0.038
    shoulder:
      radius: 0.075
      length: 0.178
    upperarm:
      radius: 0.075
      length: 0.4784
    forearm:
      radius: 0.075
      length: 0.36
    wrist_1:
      radius: 0.075
      length: 0.12
    wrist_2:
      radius: 0.075
      length: 0.12
    wrist_3:
      radius: 0.045
      length: 0.05

  center_of_mass: # model referring to https://www.universal-robots.com/how-tos-and-faqs/faq/ur-faq/parameters-for-calculations-of-kinematics-and-dynamics-45257/
    shoulder_cog:
      x: 0.0 # model.x
      y: -0.030 # -model.z
      z: -0.016 # model.y
    upper_arm_cog:
      x: -0.1764 # model.x - upperarm_length
      y: 0.0 # model.y
      z: 0.16 # model.z
    forearm_cog:
      x: -0.166 # model.x - forearm_length
      y: 0.0 # model.y
      z: 0.065 # model.z
    wrist_1_cog:
      x: 0.0 # model.x
      y: -0.011 # -model.z
      z: -0.009 # model.y
    wrist_2_cog:
      x: 0.0 # model.x
      y: 0.012 # model.z
      z: -0.018 # -model.y
    wrist_3_cog:
      x: 0.0 # model.x
      y: 0.0 # model.y
      z: -0.044 # model.z
